---
abstract: 'Use a structured execution-graph to create a test object which runs your tests smartly.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0.88
  Test::Perl::Critic: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-StructuredObject
provides:
  Test::StructuredObject:
    file: lib/Test/StructuredObject.pm
    version: 0.01000009
  Test::StructuredObject::CodeStub:
    file: lib/Test/StructuredObject/CodeStub.pm
    version: 0.01000009
  Test::StructuredObject::NonTest:
    file: lib/Test/StructuredObject/NonTest.pm
    version: 0.01000009
  Test::StructuredObject::SubTest:
    file: lib/Test/StructuredObject/SubTest.pm
    version: 0.01000009
  Test::StructuredObject::Test:
    file: lib/Test/StructuredObject/Test.pm
    version: 0.01000009
  Test::StructuredObject::TestSuite:
    file: lib/Test/StructuredObject/TestSuite.pm
    version: 0.01000009
requires:
  B::Deparse: 0
  Carp: 0
  Moose: 0
  Sub::Exporter: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  homepage: http://github.com/kentfredric/Test-StructuredObject/tree
  repository: git://github.com/kentfredric/Test-StructuredObject.git
version: 0.01000009
x_BuiltWith:
  modules:
    B::Deparse: 0.97
    Carp: 1.16
    File::Find: 1.15
    File::Temp: 0.22
    FindBin: 1.50
    Module::Build: 0.3607
    Moose: 1.08
    Sub::Exporter: 0.982
    Test::More: 0.94
    Test::Perl::Critic: 1.02
    namespace::autoclean: 0.11
  perl: 5.012001
  platform: linux
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion::Relative
      name: '@KENTNL/AutoVersion::Relative'
      version: 0.01027903
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@KENTNL/GatherDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@KENTNL/MetaConfig'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@KENTNL/PruneCruft'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@KENTNL/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::License
      name: '@KENTNL/License'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@KENTNL/PkgVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@KENTNL/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@KENTNL/MetaProvides::Package'
      version: 1.10027802
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@KENTNL/MetaJSON'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@KENTNL/MetaYAML'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@KENTNL/ModuleBuild'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@KENTNL/ReadmeFromPod'
      version: 0.12
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@KENTNL/ManifestSkip'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@KENTNL/Manifest'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@KENTNL/AutoPrereq'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      name: '@KENTNL/MetaData::BuiltWith'
      version: 0.01000216
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@KENTNL/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@KENTNL/MetaTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@KENTNL/PodCoverageTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@KENTNL/PodSyntaxTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@KENTNL/ReportVersions::Tiny'
      version: 1.01
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@KENTNL/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@KENTNL/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@KENTNL/ExtraTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@KENTNL/TestRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@KENTNL/ConfirmRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@KENTNL/Git::Check'
      version: 1.102020
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@KENTNL/NextRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag'
      version: 1.102020
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@KENTNL/Git::Commit'
      version: 1.102020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@KENTNL/UploadToCPAN'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@KENTNL/Twitter'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101900
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.101900
